AWSTemplateFormatVersion: 2010-09-09
Description: >-
  strava-shoes

Transform: AWS::Serverless-2016-10-31

Parameters:
  ClientId:
    Type: Number
    Description: "Strava app client ID"
    Default: "0"
  ClientSecret:
    Type: String
    Description: "Strava app client secret"
    NoEcho: true
    Default: ""
  AthleteId:
    Type: Number
    Description: "Strava athlete ID"
    Default: "0"

Resources:
  ShoeCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that checks the shoes assigned to Strava activities
      Runtime: nodejs14.x
      Handler: src/handlers/check.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 18 * * ? *)
      MemorySize: 128
      Timeout: 5

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default

  StravaAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that handles Strava auth callback
      Runtime: nodejs14.x
      Handler: src/handlers/auth.handler
      MemorySize: 128
      Timeout: 5
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /auth

  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "Strava shoes notification topic"
      FifoTopic: false
      TopicName: "strava-shoes-topic"

  TopicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/strava/topicId"
      Value: !Ref NotificationTopic
      Type: String
      Tier: "Standard"
      DataType: "text"

  ClientIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/strava/clientId"
      Value: !Ref ClientId
      Type: String
      Tier: "Standard"
      DataType: "text"

  ClientSecretParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/strava/clientSecret"
      Value: !Ref ClientSecret
      Type: String
      Tier: "Standard"
      DataType: "text"

  AccessTokenParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/strava/accessToken"
      Value: "placeholder"
      Type: String
      Tier: "Standard"
      DataType: "text"

  RefreshTokenParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/strava/refreshToken"
      Value: "placeholder"
      Type: String
      Tier: "Standard"
      DataType: "text"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: StravaShoesLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "logs:CreateLogGroup"
                Resource: !Join [ "", [ "arn:aws:logs:eu-west-1:", !Ref AWS::AccountId, ":*" ] ]
              - Effect: Allow
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Join [ "", [ "arn:aws:logs:", !Ref AWS::Region, ":", !Ref AWS::AccountId, ":log-group:/aws/lambda/*" ] ]
              - Effect: Allow
                Action:
                  - "ssm:PutParameter"
                  - "ssm:GetParameters"
                  - "ssm:GetParametersByPath"
                  - "ssm:DescribeParameters"
                Resource: !Join ["", ["arn:aws:ssm:", !Ref AWS::Region, ":", !Ref AWS::AccountId, ":parameter/strava*"]]
              - Effect: Allow
                Action: "sns:Publish"
                Resource: !Ref NotificationTopic

Outputs:
  AuthCallbackDomain:
    Description: Authorization callback domain (set in Strava app)
    Value:
      Fn::Join:
        - ''
        - - Ref: HttpApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com
  StravaAuthUrl:
    Description: URL to visit to authenticate
    Value:
      Fn::Join:
        - ''
        - - https://www.strava.com/oauth/authorize?client_id=
          - Ref: ClientId
          - '&response_type=code&redirect_uri=https://'
          - Ref: HttpApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/auth&scope=activity:read
