on:
  workflow_call:
    inputs:
      upload:
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pro
    permissions:
      id-token: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "go.mod"

      - name: Download Go packages
        shell: bash
        run: |
          go get ./...
        env:
          GONOPROXY: "github.com/ockendenjo/*"

      - name: Build commands
        shell: bash
        run: |
          go run ./scripts/build-cmd --zip
        env:
          GONOPROXY: "github.com/ockendenjo/*"

      - name: configure aws credentials
        if: ${{ inputs.upload }}
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true

      - name: Upload artifacts
        if: ${{ inputs.upload }}
        shell: bash
        run: |
          go run ./scripts/upload-binaries
        env:
          BINARY_BUCKET: ${{ secrets.BINARY_BUCKET }}
