name: main

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: false

permissions: {}

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yaml

  build:
    permissions:
      contents: read
      id-token: write
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BINARY_BUCKET: ${{ secrets.BINARY_BUCKET }}
    uses: ./.github/workflows/build.yaml
    with:
      upload: true

  deploy:
    permissions:
      contents: read
      id-token: write
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
    needs: [build, test]
    uses: ./.github/workflows/tf.yaml
    with:
      apply: true
