name: SAST
on:
  pull_request: {}
  schedule:
    - cron: "35 9 * * *"

permissions: {}

jobs:
  sast:
    permissions:
      contents: read
    uses: ockendenjo/actions/.github/workflows/sast.yaml@8ae3d2247a26d789fa4894c40f69d1163df4c1cb # v2027.07.21
