name: SAST
on:
  pull_request: {}
  schedule:
    - cron: "35 9 * * *"

permissions: {}

jobs:
  sast:
    permissions:
      contents: read
    uses: ockendenjo/actions/.github/workflows/sast.yaml@18e61688fd7fa5223adc34faad6cc58522edd718 # v2026.06.03
