on:
  workflow_call:
    inputs:
      apply:
        type: boolean
        default: false
    secrets:
      AWS_ROLE_ARN:
        required: true
      AWS_REGION:
        required: true
      TF_STATE_BUCKET:
        required: true

jobs:
  tf:
    runs-on: ubuntu-latest
    environment: pro
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true

      - name: get terraform config
        working-directory: stack
        run: |
          mkdir -p tfvars
          aws s3 sync s3://${{ secrets.TF_STATE_BUCKET }}/tfvars/ tfvars/

      - name: init
        working-directory: stack
        run: |
          terraform init -backend-config=tfvars/backend-pro.hcl

      - name: plan
        if: ${{ !inputs.apply }}
        working-directory: stack
        run: |
          terraform plan -var-file="tfvars/pro.tfvars"

      - name: apply
        if: ${{ inputs.apply }}
        working-directory: stack
        run: |
          terraform apply -auto-approve -var-file="tfvars/pro.tfvars"
